# Generated by Django 5.1.7 on 2025-03-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_bio', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='student_pictures/')),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
