# Generated by Django 5.1.7 on 2025-03-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_Name', models.CharField(max_length=255)),
                ('child_name', models.CharField(max_length=255)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('child_age', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
