# Generated by Django 5.1.7 on 2025-03-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
