# Generated by Django 4.2.11 on 2025-03-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('child_name', models.CharField(max_length=255)),
                ('child_age', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
